### ISSUE TITLE
Go through config structs and ensure sane values are present

### ISSUE THREAD

**Issue by bradleynull** [monoDriveIO/monodrive-client#32]
This should be done for each sensor as well as the simulator and weather configurations. Referencing the LabVIEW client would probably be the best way to get the current best values.

**Comment by stephendb** [comment]
This should be part of a test harness where the defaults are more permanent since the defaults might be changed causing issue.

**Comment by devinaconley** [comment]
Closing this as completed. Will track integrating this check in a test framework separately.
