### ISSUE TITLE
Update Multiple Vehicle Control.

### ISSUE THREAD

**Issue by bradleynull** [monoDriveIO/monodrive-client#4]
In order to connect multiple ROS nodes of the same type to servers running on different ports, the node names need to be different. Currently running multiple `simulator_control` nodes or multiple `vehicle_control` nodes results in:

```
[ WARN] [1586788781.889340082]: Shutdown request received.
[ WARN] [1586788781.890005020]: Reason given for shutdown: [new node registered with same name]
```

**NOTE:** The use case for this is when running multiple simulators on the same machine using [this PR](https://github.com/monoDriveIO/simulator/pull/70)

**Comment by stephendb** [comment]
Obsolete architecture.
